In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 


dataset = pd.read_csv("../data/raw/dataset-6ab989b678d90892980305.csv")

In [4]:
# removing one missing values (discoved in EDA)

dataset.dropna(subset=["CREDIT_LIMIT"] , inplace=True)
dataset.loc[dataset["CREDIT_LIMIT"].isna()]

Empty DataFrame
Columns: [CUST_ID, BALANCE, PURCHASES, ONEOFF_PURCHASES, INSTALLMENTS_PURCHASES, CASH_ADVANCE, CREDIT_LIMIT, PAYMENTS]
Index: []

In [ ]:
# outliers transformation wiht log1p :  

columns = dataset.drop(columns="CUST_ID").columns

for column in columns : 
    dataset[column] = np.log1p(dataset[column])
dataset

,CUST_ID,BALANCE,PURCHASES,ONEOFF_PURCHASES,INSTALLMENTS_PURCHASES,CASH_ADVANCE,CREDIT_LIMIT,PAYMENTS
0,C10001,3.735304,4.568506,0.000000,4.568506,0.000000,6.908755,5.312231
1,C10002,8.071989,0.000000,0.000000,0.000000,8.770896,8.853808,8.319725
2,C10003,7.822504,6.651791,6.651791,0.000000,0.000000,8.922792,6.434654
3,C10004,7.419183,7.313220,7.313220,0.000000,5.331694,8.922792,0.000000
4,C10005,6.707735,2.833213,2.833213,0.000000,0.000000,7.090910,6.521114
...,...,...,...,...,...,...,...,...
8945,C19186,3.384170,5.677165,0.000000,5.677165,0.000000,6.908755,5.788719
8946,C19187,3.004851,5.707110,0.000000,5.707110,0.000000,6.908755,5.623517
8947,C19188,3.194529,4.979489,0.000000,4.979489,0.000000,6.908755,4.410016
8948,C19189,2.671218,0.000000,0.000000,0.000000,3.625907,6.216606,3.980615
8949,C19190,5.923475,6.997824,6.997824,0.000000,4.852343,7.090910,4.161464